# Generated by Django 5.0.6 on 2024-07-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (optional)', null=True, upload_to='media/'),
        ),
    ]
