# Generated by Django 4.2.13 on 2024-07-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (optional)', null=True, upload_to='product_images/'),
        ),
    ]
