# Generated by Django 4.2.13 on 2024-06-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_category_remove_siteuser_name_siteuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='password',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
