# Generated by Django 4.2.13 on 2024-06-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_siteuser_options_remove_siteuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1)),
                ('siteuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.siteuser')),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='siteuser',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.AddField(
            model_name='category',
            name='highlighted_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.products'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='store.products')),
            ],
        ),
    ]
