# Generated by Django 4.2.13 on 2024-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shoppingcart_review_shoppingcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
