# Generated by Django 4.2.13 on 2024-06-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_siteuser_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='ShoppingOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ShoppingOrderItem',
        ),
    ]
