# Generated by Django 4.2.13 on 2024-07-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_shoppingorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='store.shoppingcart'),
        ),
    ]
